name: CI

on:
  #manually trigger runs
  workflow_dispatch:

jobs:
   build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         # clang++ cct.cc -g -o a.out -Wall
         # sudo apt-get install valgrind
         # valgrind ./a.out
         clang++ cct.cc  -o a.out -Wall
         ./a.out 10
